// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace tilesim {
	
	
	public partial class Game {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected tilesim.CurrentActivityPanel CurrentActivity;
		
		protected tilesim.StartActivityPanel StartActivity;
		
		protected tilesim.PlayerPanel Player;
		
		protected tilesim.LogPanel Log;
		
		protected tilesim.MapPanel Map;
		
		protected tilesim.GameInfoPanel GameInfo;
		
		protected tilesim.TilePanel CurrentTile;
	}
}
